server:
  port: 8080

spring:
  config:
    import:
      - 'classpath:config/aws.yml'
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: test
      password: test123
      database: aws_test
      authentication-database: admin
      auto-index-creation: true
      repositories:
        type: reactive
